# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24bdefb77e7d500cd6f3a91d803cb11b"
application_url = "https://informative-ontario-portugal-belfast.trycloudflare.com"
embedded = true
name = "data-customer"
handle = "data-customer"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products,write_orders,read_orders,read_customer_events,read_delivery_customizations,write_delivery_customizations,read_draft_orders,write_draft_orders,read_fulfillments,write_fulfillments,read_order_edits,write_order_edits,read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://informative-ontario-portugal-belfast.trycloudflare.com/auth/callback",
  "https://informative-ontario-portugal-belfast.trycloudflare.com/auth/shopify/callback",
  "https://informative-ontario-portugal-belfast.trycloudflare.com/api/auth/callback",
  "https://app.customercloudhq.com//shopify/callback"
"]

[pos]
embedded = false

[build]
dev_store_url = "customers-store1.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
